# Generated by Django 4.0.2 on 2022-11-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_filed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageRange', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
