# Generated by Django 4.0.2 on 2022-11-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nationalID', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('age', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.career')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.district')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.gender')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.level_of_education')),
                ('living', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.living_con')),
                ('subdictrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subdictrict')),
            ],
        ),
    ]
