# Generated by Django 4.0.2 on 2022-11-02 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_filed'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.filed'),
            preserve_default=False,
        ),
    ]
