# Generated by Django 4.0.2 on 2022-11-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_filed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='relationship',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
