# Generated by Django 4.0.2 on 2022-11-02 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_agerange'),
        ('blog', '0003_post_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ageRange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.agerange'),
            preserve_default=False,
        ),
    ]
